-- WNMU-FM only: historical schedules transcribed from WNMU-FM Preview newsletters.
create table if not exists public.wnmufm_schedule_newsletter_sources (
  id bigint generated by default as identity primary key,
  source_key text not null unique,
  issue_month date not null unique,
  listings_current_as_of date,
  title text not null,
  source_type text not null default 'WNMU-FM Preview newsletter',
  file_name text not null,
  file_sha256 text not null,
  file_size_bytes bigint not null,
  schedule_page smallint not null,
  timezone text not null default 'America/Detroit',
  notes text,
  created_at timestamptz not null default now(),
  constraint wnmufm_schedule_newsletter_sources_hash check (file_sha256 ~ '^[0-9a-f]{64}$')
);

create table if not exists public.wnmufm_schedule_newsletter_entries (
  id bigint generated by default as identity primary key,
  entry_key text not null unique,
  source_id bigint not null references public.wnmufm_schedule_newsletter_sources(id) on delete cascade,
  issue_month date not null,
  entry_type text not null,
  specific_date date,
  weekday smallint,
  effective_start date,
  effective_end date,
  start_time time not null,
  end_time time,
  program_title text not null,
  replaces_program_title text,
  source_page smallint not null,
  confidence text not null default 'high',
  notes text,
  created_at timestamptz not null default now(),
  constraint wnmufm_schedule_newsletter_entries_type check (entry_type in ('recurring','dated_override','embedded_feature')),
  constraint wnmufm_schedule_newsletter_entries_weekday check (weekday is null or weekday between 0 and 6),
  constraint wnmufm_schedule_newsletter_entries_confidence check (confidence in ('high','medium','low')),
  constraint wnmufm_schedule_newsletter_entries_effective_dates check (effective_end is null or effective_start is null or effective_end >= effective_start)
);

create index if not exists wnmufm_schedule_newsletter_entries_month_idx
  on public.wnmufm_schedule_newsletter_entries(issue_month);
create index if not exists wnmufm_schedule_newsletter_entries_date_idx
  on public.wnmufm_schedule_newsletter_entries(specific_date);
create index if not exists wnmufm_schedule_newsletter_entries_week_time_idx
  on public.wnmufm_schedule_newsletter_entries(weekday,start_time);

alter table public.wnmufm_schedule_newsletter_sources enable row level security;
alter table public.wnmufm_schedule_newsletter_entries enable row level security;

create policy "WNMU FM newsletter schedule sources read"
  on public.wnmufm_schedule_newsletter_sources for select to authenticated
  using (public.wnmufm_has_analytics_role(array['viewer','editor','admin']));
create policy "WNMU FM newsletter schedule sources insert"
  on public.wnmufm_schedule_newsletter_sources for insert to authenticated
  with check (public.wnmufm_has_analytics_role(array['editor','admin']));
create policy "WNMU FM newsletter schedule sources update"
  on public.wnmufm_schedule_newsletter_sources for update to authenticated
  using (public.wnmufm_has_analytics_role(array['editor','admin']))
  with check (public.wnmufm_has_analytics_role(array['editor','admin']));
create policy "WNMU FM newsletter schedule sources delete"
  on public.wnmufm_schedule_newsletter_sources for delete to authenticated
  using (public.wnmufm_has_analytics_role(array['admin']));

create policy "WNMU FM newsletter schedule entries read"
  on public.wnmufm_schedule_newsletter_entries for select to authenticated
  using (public.wnmufm_has_analytics_role(array['viewer','editor','admin']));
create policy "WNMU FM newsletter schedule entries insert"
  on public.wnmufm_schedule_newsletter_entries for insert to authenticated
  with check (public.wnmufm_has_analytics_role(array['editor','admin']));
create policy "WNMU FM newsletter schedule entries update"
  on public.wnmufm_schedule_newsletter_entries for update to authenticated
  using (public.wnmufm_has_analytics_role(array['editor','admin']))
  with check (public.wnmufm_has_analytics_role(array['editor','admin']));
create policy "WNMU FM newsletter schedule entries delete"
  on public.wnmufm_schedule_newsletter_entries for delete to authenticated
  using (public.wnmufm_has_analytics_role(array['admin']));

comment on table public.wnmufm_schedule_newsletter_sources is
  'WNMU-FM-only provenance records for historical schedules mined from WNMU-FM Preview newsletters.';
comment on table public.wnmufm_schedule_newsletter_entries is
  'WNMU-FM-only normalized recurring schedule blocks and dated overrides transcribed from Preview newsletters. Weekday uses 0=Sunday through 6=Saturday and midnight-5am newsletter-grid blocks are normalized to the actual calendar weekday.';
