-- WNMU-FM analytics foundation.
-- FM-owned objects use the wnmufm_ prefix so they cannot be confused with WNMU-TV data.

create or replace function public.wnmufm_has_analytics_role(allowed_roles text[] default array['viewer','editor','admin']::text[])
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1
    from public.wnmu_app_user_roles r
    where r.is_active = true
      and r.app_key = 'wnmufm_analytics'
      and lower(r.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
      and r.role = any(allowed_roles)
  );
$$;

revoke all on function public.wnmufm_has_analytics_role(text[]) from public;
revoke execute on function public.wnmufm_has_analytics_role(text[]) from anon;
grant execute on function public.wnmufm_has_analytics_role(text[]) to authenticated;

create table if not exists public.wnmufm_analytics_imports (
  id bigint generated by default as identity primary key,
  source_sha256 text not null unique,
  source_filename text not null,
  report_type text not null check (report_type in ('audio_downloads','audio_program_drilldown','station_streaming','station_website','npr_one','audience_leads','unknown')),
  grain text not null check (grain in ('day','week','month','unknown')),
  station_key text not null default 'wnmu_fm',
  station_name text not null default 'WNMU',
  service_name text,
  report_start date,
  report_end date,
  filter_context jsonb not null default '{}'::jsonb,
  selected_program text,
  status text not null default 'imported' check (status in ('imported','partial','rejected')),
  row_count integer not null default 0 check (row_count >= 0),
  parser_version text not null,
  imported_by_email text,
  imported_at timestamptz not null default now(),
  notes text
);

create table if not exists public.wnmufm_analytics_raw_rows (
  id bigint generated by default as identity primary key,
  import_id bigint not null references public.wnmufm_analytics_imports(id) on delete cascade,
  csv_name text not null,
  row_number integer not null check (row_number >= 1),
  row_data jsonb not null,
  created_at timestamptz not null default now(),
  unique(import_id, csv_name, row_number)
);

create table if not exists public.wnmufm_analytics_observations (
  id bigint generated by default as identity primary key,
  station_key text not null default 'wnmu_fm',
  report_type text not null,
  grain text not null check (grain in ('day','week','month','unknown')),
  period_start date not null,
  period_end date not null,
  metric_key text not null,
  metric_label text not null,
  unit text not null default 'count',
  dimension_type text not null default '',
  dimension_value text not null default '',
  filter_signature text not null default '',
  station_value numeric,
  benchmark_value numeric,
  benchmark_label text,
  text_value text,
  source_import_id bigint references public.wnmufm_analytics_imports(id) on delete set null,
  source_csv text not null,
  source_row integer,
  quality_flags text[] not null default '{}'::text[],
  updated_at timestamptz not null default now(),
  constraint wnmufm_analytics_observations_identity_key unique (
    station_key, report_type, grain, period_start, period_end, metric_key,
    dimension_type, dimension_value, filter_signature
  )
);

create table if not exists public.wnmufm_analytics_anomalies (
  id bigint generated by default as identity primary key,
  observation_id bigint references public.wnmufm_analytics_observations(id) on delete cascade,
  import_id bigint references public.wnmufm_analytics_imports(id) on delete cascade,
  anomaly_key text not null,
  severity text not null default 'info' check (severity in ('info','warning','high')),
  status text not null default 'open' check (status in ('open','expected','excluded','resolved')),
  title text not null,
  detail text,
  evidence jsonb not null default '{}'::jsonb,
  detected_at timestamptz not null default now(),
  reviewed_by_email text,
  reviewed_at timestamptz
);

create index if not exists wnmufm_obs_metric_period_idx on public.wnmufm_analytics_observations (report_type, metric_key, grain, period_start);
create index if not exists wnmufm_obs_dimension_idx on public.wnmufm_analytics_observations (report_type, dimension_type, dimension_value, period_start);
create index if not exists wnmufm_raw_import_idx on public.wnmufm_analytics_raw_rows (import_id, csv_name);
create index if not exists wnmufm_anomaly_status_idx on public.wnmufm_analytics_anomalies (status, severity, detected_at desc);

alter table public.wnmufm_analytics_imports enable row level security;
alter table public.wnmufm_analytics_raw_rows enable row level security;
alter table public.wnmufm_analytics_observations enable row level security;
alter table public.wnmufm_analytics_anomalies enable row level security;

drop policy if exists "WNMU FM analytics imports read" on public.wnmufm_analytics_imports;
create policy "WNMU FM analytics imports read" on public.wnmufm_analytics_imports for select to authenticated using (public.wnmufm_has_analytics_role(array['viewer','editor','admin']::text[]));
drop policy if exists "WNMU FM analytics imports insert" on public.wnmufm_analytics_imports;
create policy "WNMU FM analytics imports insert" on public.wnmufm_analytics_imports for insert to authenticated with check (public.wnmufm_has_analytics_role(array['editor','admin']::text[]));
drop policy if exists "WNMU FM analytics imports update" on public.wnmufm_analytics_imports;
create policy "WNMU FM analytics imports update" on public.wnmufm_analytics_imports for update to authenticated using (public.wnmufm_has_analytics_role(array['editor','admin']::text[])) with check (public.wnmufm_has_analytics_role(array['editor','admin']::text[]));
drop policy if exists "WNMU FM analytics imports delete" on public.wnmufm_analytics_imports;
create policy "WNMU FM analytics imports delete" on public.wnmufm_analytics_imports for delete to authenticated using (public.wnmufm_has_analytics_role(array['admin']::text[]));

drop policy if exists "WNMU FM analytics raw read" on public.wnmufm_analytics_raw_rows;
create policy "WNMU FM analytics raw read" on public.wnmufm_analytics_raw_rows for select to authenticated using (public.wnmufm_has_analytics_role(array['viewer','editor','admin']::text[]));
drop policy if exists "WNMU FM analytics raw insert" on public.wnmufm_analytics_raw_rows;
create policy "WNMU FM analytics raw insert" on public.wnmufm_analytics_raw_rows for insert to authenticated with check (public.wnmufm_has_analytics_role(array['editor','admin']::text[]));
drop policy if exists "WNMU FM analytics raw delete" on public.wnmufm_analytics_raw_rows;
create policy "WNMU FM analytics raw delete" on public.wnmufm_analytics_raw_rows for delete to authenticated using (public.wnmufm_has_analytics_role(array['admin']::text[]));

drop policy if exists "WNMU FM analytics observations read" on public.wnmufm_analytics_observations;
create policy "WNMU FM analytics observations read" on public.wnmufm_analytics_observations for select to authenticated using (public.wnmufm_has_analytics_role(array['viewer','editor','admin']::text[]));
drop policy if exists "WNMU FM analytics observations insert" on public.wnmufm_analytics_observations;
create policy "WNMU FM analytics observations insert" on public.wnmufm_analytics_observations for insert to authenticated with check (public.wnmufm_has_analytics_role(array['editor','admin']::text[]));
drop policy if exists "WNMU FM analytics observations update" on public.wnmufm_analytics_observations;
create policy "WNMU FM analytics observations update" on public.wnmufm_analytics_observations for update to authenticated using (public.wnmufm_has_analytics_role(array['editor','admin']::text[])) with check (public.wnmufm_has_analytics_role(array['editor','admin']::text[]));
drop policy if exists "WNMU FM analytics observations delete" on public.wnmufm_analytics_observations;
create policy "WNMU FM analytics observations delete" on public.wnmufm_analytics_observations for delete to authenticated using (public.wnmufm_has_analytics_role(array['admin']::text[]));

drop policy if exists "WNMU FM analytics anomalies read" on public.wnmufm_analytics_anomalies;
create policy "WNMU FM analytics anomalies read" on public.wnmufm_analytics_anomalies for select to authenticated using (public.wnmufm_has_analytics_role(array['viewer','editor','admin']::text[]));
drop policy if exists "WNMU FM analytics anomalies insert" on public.wnmufm_analytics_anomalies;
create policy "WNMU FM analytics anomalies insert" on public.wnmufm_analytics_anomalies for insert to authenticated with check (public.wnmufm_has_analytics_role(array['editor','admin']::text[]));
drop policy if exists "WNMU FM analytics anomalies update" on public.wnmufm_analytics_anomalies;
create policy "WNMU FM analytics anomalies update" on public.wnmufm_analytics_anomalies for update to authenticated using (public.wnmufm_has_analytics_role(array['editor','admin']::text[])) with check (public.wnmufm_has_analytics_role(array['editor','admin']::text[]));
drop policy if exists "WNMU FM analytics anomalies delete" on public.wnmufm_analytics_anomalies;
create policy "WNMU FM analytics anomalies delete" on public.wnmufm_analytics_anomalies for delete to authenticated using (public.wnmufm_has_analytics_role(array['admin']::text[]));

grant select, insert, update, delete on public.wnmufm_analytics_imports to authenticated;
grant select, insert, delete on public.wnmufm_analytics_raw_rows to authenticated;
grant select, insert, update, delete on public.wnmufm_analytics_observations to authenticated;
grant select, insert, update, delete on public.wnmufm_analytics_anomalies to authenticated;
grant usage, select on sequence public.wnmufm_analytics_imports_id_seq to authenticated;
grant usage, select on sequence public.wnmufm_analytics_raw_rows_id_seq to authenticated;
grant usage, select on sequence public.wnmufm_analytics_observations_id_seq to authenticated;
grant usage, select on sequence public.wnmufm_analytics_anomalies_id_seq to authenticated;
