create extension if not exists pg_net;
create extension if not exists pg_cron;

create table if not exists public.wnmufm_schedule_catalog_versions (
  id bigint generated by default as identity primary key,
  payload_hash text not null unique,
  payload jsonb not null,
  source_url text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint wnmufm_schedule_catalog_versions_hash_nonblank check (btrim(payload_hash) <> '')
);

create table if not exists public.wnmufm_schedule_daily_archive (
  capture_date date primary key,
  captured_at timestamptz not null default now(),
  catalog_version_id bigint not null references public.wnmufm_schedule_catalog_versions(id) on delete restrict,
  created_at timestamptz not null default now()
);

create index if not exists wnmufm_schedule_daily_archive_version_idx
  on public.wnmufm_schedule_daily_archive(catalog_version_id);

alter table public.wnmufm_schedule_catalog_versions enable row level security;
alter table public.wnmufm_schedule_daily_archive enable row level security;

comment on table public.wnmufm_schedule_catalog_versions is
  'Deduplicated snapshots of the NPR Composer recurring WNMU-FM schedule catalog. Used to preserve schedule history going forward when Composer historical episodes are unavailable.';

comment on table public.wnmufm_schedule_daily_archive is
  'One daily pointer to the recurring Composer catalog version captured for WNMU-FM. A daily archive preserves when recurring schedule definitions changed without duplicating the full payload every day.';

select cron.schedule(
  'wnmufm_schedule_archive_daily',
  '5 10 * * *',
  $cron$
    select net.http_get(
      url := 'https://tdepltlnughyfrjqufdg.supabase.co/functions/v1/wnmufm-composer-schedule?start='
        || to_char((now() at time zone 'America/Detroit')::date, 'YYYY-MM-DD')
        || '&end='
        || to_char((now() at time zone 'America/Detroit')::date, 'YYYY-MM-DD'),
      timeout_milliseconds := 15000
    );
  $cron$
);
